/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youchat;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author geneowak
 */
public class SendBroadcastMsg extends javax.swing.JPanel {

    private JFrame parent;
    public SendBroadcastMsg(JFrame parentFrame) {
        initComponents();
        this.parent = parentFrame;
        this.msgArea.setForeground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        msgArea.setColumns(20);
        msgArea.setRows(5);
        msgArea.setText("Enter your broadcast message here");
        msgArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msgAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msgAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(msgArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(sendButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String content = this.msgArea.getText();
        YouChatMain owner = (YouChatMain)parent;
        if(!content.isEmpty())
        {
            BroadCast sender = new BroadCast(owner.verified.username,content);
            if(sender.sendMessage())
            {
                JOptionPane.showMessageDialog(parent, "The message has been broadcasted to "+sender.getCount()+" people");
                this.msgArea.setText("Enter your broadcast message here");
                msgArea.setForeground(Color.lightGray);
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void msgAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgAreaFocusGained
        msgArea.setText("");
        msgArea.setForeground(Color.BLACK);
    }//GEN-LAST:event_msgAreaFocusGained

    private void msgAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgAreaFocusLost
        String content = this.msgArea.getText();
        if(content.isEmpty())
        {
            this.msgArea.setText("Enter your broadcast message here");
            msgArea.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_msgAreaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgArea;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
